import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
  // console.log(navigator.userAgent);
  const [userData, setUserData] = useState();

  useEffect(() => {
    console.log(navigator);
    setUserData(
      navigator.userAgent + " ismobile? " + navigator.userAgentData.mobile
    );

    // return () => {
    //   second
    // }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{userData}</h1>

      <Header />
    </div>
  );
}
